//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vinci_novo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string tituloen { get; set; }
        public string link { get; set; }
        public string imagem { get; set; }
        public int ativo { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<int> ordem { get; set; }
    }
}
