//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vinci_novo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vinci_novoEntities : DbContext
    {
        public vinci_novoEntities()
            : base("name=vinci_novoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<risks> risks { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<numbers> numbers { get; set; }
        public virtual DbSet<families> families { get; set; }
        public virtual DbSet<institutions> institutions { get; set; }
        public virtual DbSet<highlights> highlights { get; set; }
        public virtual DbSet<txts> txts { get; set; }
        public virtual DbSet<valors> valors { get; set; }
        public virtual DbSet<partners> partners { get; set; }
        public virtual DbSet<news> news { get; set; }
    }
}
